### ISSUE TITLE
Recent commit causes AtlasProject creation to fail

### ISSUE THREAD

**Issue by jianrongzhang89** [mongodb/mongodb-atlas-kubernetes#452] opened 2022-03-03 17:38 UTC
**What did you do to encounter the bug?**
1) Build Atlas Operator from the main branch as of March 2, 2022.
2) Deploy the operator with OLM on an OpenShift 4.9 cluster.
3) Create a connection secret and an AtlasProject CR:
apiVersion: atlas.mongodb.com/v1
kind: AtlasProject
metadata:
  name: jianrzha
spec:
  connectionSecretRef:
    name: my-atlas-key
  name: jianrzha
  projectIpAccessList:
    - comment: IP address for Application Server A
      ipAddress: 192.0.2.15
    - comment: CIDR block for Application Server B - D
      ipAddress: 203.0.113.0/24
4) The CR status shows failure:
status:
  conditions:
  - lastTransitionTime: "2022-03-03T16:48:33Z"
    status: "False"
    type: Ready
  - lastTransitionTime: "2022-03-03T16:48:33Z"
    status: "True"
    type: ValidationSucceeded
  - lastTransitionTime: "2022-03-03T16:48:33Z"
    message: base URL must have a trailing slash, but "https://cloud.mongodb.com"
      does not
    reason: ProjectNotCreatedInAtlas
    status: "False"
    type: ProjectReady
  observedGeneration: 1

**What did you expect?**
The AtlasProject should be reconciled successfully.

**What happened instead?**
A clear and concise description of what happened instead
See above error message.

**Screenshots**

**Operator Information**
 - Operator Version: built from main branch.
**Kubernetes Cluster Information**
 - Distribution: OpenShift
 - Version: 4.9
 - Image Registry location (quay, or an internal registry)

**Additional context**
This issue seems to be caused by a recent commit: 
https://github.com/mongodb/mongodb-atlas-kubernetes/commit/b5237e882b628619a99c92474642dce40f310314 

If possible, please include:
 - `kubectl describe` output
 - yaml definitions for your objects
 - log files for the operator and database pods

**Comment by igor-karpukhin** [comment] 2022-03-03 22:14
Hello @jianrongzhang89 thanks for the issue. The problem is with the bumped up atlas library, it is now expects only URLs with trailing backslash. You can quickly fix your deployment by setting `--atlas-domain` parameter to `https://cloud.mongodb.com/`. We will provide a PR with fix soon.

**Comment by jianrongzhang89** [comment] 2022-03-03 22:35
@igor-karpukhin thanks for looking into this issue.
Here is the data for the CR:
kubectl get atlasproject.atlas.mongodb.com/jianrzha -o yaml
apiVersion: atlas.mongodb.com/v1
kind: AtlasProject
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"atlas.mongodb.com/v1","kind":"AtlasProject","metadata":{"annotations":{},"name":"jianrzha","namespace":"openshift-dbaas-operator"},"spec":{"connectionSecretRef":{"name":"my-atlas-key"},"name":"jianrzha","projectIpAccessList":[{"comment":"IP address for Application Server A","ipAddress":"192.0.2.15"},{"comment":"CIDR block for Application Server B - D","ipAddress":"203.0.113.0/24"}]}}
  creationTimestamp: "2022-03-03T22:31:20Z"
  generation: 1
  managedFields:
  - apiVersion: atlas.mongodb.com/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:connectionSecretRef:
          .: {}
          f:name: {}
        f:name: {}
        f:projectIpAccessList: {}
        f:withDefaultAlertsSettings: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2022-03-03T22:31:20Z"
  - apiVersion: atlas.mongodb.com/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:conditions: {}
        f:observedGeneration: {}
    manager: manager
    operation: Update
    subresource: status
    time: "2022-03-03T22:31:20Z"
  name: jianrzha
  namespace: openshift-dbaas-operator
  resourceVersion: "754179"
  uid: eb354f2c-9eb4-4208-bc98-13a53039e292
spec:
  connectionSecretRef:
    name: my-atlas-key
  name: jianrzha
  projectIpAccessList:
  - comment: IP address for Application Server A
    ipAddress: 192.0.2.15
  - comment: CIDR block for Application Server B - D
    ipAddress: 203.0.113.0/24
  withDefaultAlertsSettings: true
status:
  conditions:
  - lastTransitionTime: "2022-03-03T22:31:20Z"
    status: "False"
    type: Ready
  - lastTransitionTime: "2022-03-03T22:31:20Z"
    status: "True"
    type: ValidationSucceeded
  - lastTransitionTime: "2022-03-03T22:31:20Z"
    message: base URL must have a trailing slash, but "https://cloud.mongodb.com"
      does not
    reason: ProjectNotCreatedInAtlas
    status: "False"
    type: ProjectReady
  observedGeneration: 1

and operator log:
1.6463466807191522e+09	DEBUG	controllers.AtlasProject	Watching openshift-dbaas-operator/my-atlas-key (Secret) to trigger reconciliation for openshift-dbaas-operator/jianrzha	{"atlasproject": "openshift-dbaas-operator/jianrzha"}
1.6463466807279584e+09	INFO	controllers.AtlasProject	-> Starting AtlasProject reconciliation	{"atlasproject": "openshift-dbaas-operator/jianrzha", "spec": {"name":"jianrzha","connectionSecretRef":{"name":"my-atlas-key"},"projectIpAccessList":[{"comment":"IP address for Application Server A","ipAddress":"192.0.2.15"},{"comment":"CIDR block for Application Server B - D","ipAddress":"203.0.113.0/24"}],"withDefaultAlertsSettings":true}}
1.6463466807280474e+09	INFO	controllers.AtlasProject	Reading Atlas API credentials from the AtlasProject Secret openshift-dbaas-operator/my-atlas-key	{"atlasproject": "openshift-dbaas-operator/jianrzha"}
1.64634668072817e+09	INFO	controllers.AtlasProject	Error	{"atlasproject": "openshift-dbaas-operator/jianrzha", "err": "base URL must have a trailing slash, but \"https://cloud.mongodb.com\" does not"}
1.6463466807282004e+09	INFO	controllers.AtlasProject	Status update	{"atlasproject": "openshift-dbaas-operator/jianrzha", "lastCondition": {"type":"ProjectReady","status":"False","lastTransitionTime":null,"reason":"ProjectNotCreatedInAtlas","message":"base URL must have a trailing slash, but \"https://cloud.mongodb.com\" does not"}}

**Comment by jamesbroadhead** [comment] 2022-03-04 17:34
@jianrongzhang89 thank you for this report - we believe that it was fixed in #453

**Closed by jamesbroadhead** 2022-03-04 17:34 UTC
