### ISSUE TITLE
Operator crashes when numShards is omitted from the AtlasDeployment resource

### ISSUE THREAD

**Issue by viktorradnai** [mongodb/mongodb-atlas-kubernetes#1195] opened 2023-10-24 10:19 UTC
**What did you do to encounter the bug?**

We are trying to use the operator with an Atlas project and cluster that are managed by Terraform with the sole purpose of managing database users. I've created minimalist AtlasProject and AtlasDeployment custom resources like this:

```
---
apiVersion: atlas.mongodb.com/v1
kind: AtlasProject
metadata:
  name: test-uk
spec:
  name: test-uk
---
apiVersion: atlas.mongodb.com/v1
kind: AtlasDeployment
metadata:
  name: test-uk-test-uk
spec:
  advancedDeploymentSpec:
    name: test-uk
    # replicationSpecs:
    # - numShards: 1
  projectRef:
    name: test-uk
```

The goal was to add as little as possible given that this is all managed elsewhere. I've found that if I omit the `numShards` parameter (the lines commented out above) then the custom resource will pass validation but the operator will crashloop with a panic.

**What did you expect?**

I expect the operator to not manage the aspects of the database cluster I omit from the spec.

**What happened instead?**
The operator crashed with the following panic message and continued to crash after leader election each time after Kubernetes restarted it: 

```
mongodb-atlas-operator-6db86785d8-4mtsq manager {"level":"INFO","time":"2023-10-24T09:57:58.391Z","msg":"Status update","atlasdeployment":"default/test-uk-test-uk","lastCondition":{"type":"ValidationSucceeded","status":"True","lastTransitionTime":null}}
mongodb-atlas-operator-6db86785d8-4mtsq manager {"level":"INFO","time":"2023-10-24T09:57:58.405Z","msg":"Observed a panic in reconciler: runtime error: index out of range [0] with length 0","controller":"AtlasDeployment","object":{"name":"test-uk-test-uk","namespace":"default"},"namespace":"default","name":"test-uk-test-uk","reconcileID":"d96a5d1d-e829-422a-b45e-ea6c58fbd65f"}
mongodb-atlas-operator-6db86785d8-4mtsq manager panic: runtime error: index out of range [0] with length 0 [recovered]
mongodb-atlas-operator-6db86785d8-4mtsq manager 	panic: runtime error: index out of range [0] with length 0
mongodb-atlas-operator-6db86785d8-4mtsq manager 
mongodb-atlas-operator-6db86785d8-4mtsq manager goroutine 342 [running]:
mongodb-atlas-operator-6db86785d8-4mtsq manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
mongodb-atlas-operator-6db86785d8-4mtsq manager 	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:119 +0x1a4
mongodb-atlas-operator-6db86785d8-4mtsq manager panic({0x12cdc00?, 0x40008a1b60?})
mongodb-atlas-operator-6db86785d8-4mtsq manager 	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/panic.go:914 +0x218
mongodb-atlas-operator-6db86785d8-4mtsq manager github.com/mongodb/mongodb-atlas-kubernetes/pkg/controller/atlasdeployment.MergedAdvancedDeployment({0x40006cdf98, 0x4000ead638, {0x40006cdfc0, 0xa}, 0x40002f2850, 0x40006cdfd0, {0x40006cdfe0, 0x4}, {0x40008a1a70, 0x18}, ...}, ...)
mongodb-atlas-operator-6db86785d8-4mtsq manager 	/home/runner/work/mongodb-atlas-kubernetes/mongodb-atlas-kubernetes/pkg/controller/atlasdeployment/advanced_deployment.go:129 +0x300
mongodb-atlas-operator-6db86785d8-4mtsq manager github.com/mongodb/mongodb-atlas-kubernetes/pkg/controller/atlasdeployment.advancedDeploymentIdle(0x400031c500, 0x400002e000, 0x40005a2480, 0x4000de1680)
mongodb-atlas-operator-6db86785d8-4mtsq manager 	/home/runner/work/mongodb-atlas-kubernetes/mongodb-atlas-kubernetes/pkg/controller/atlasdeployment/advanced_deployment.go:81 +0x10c
mongodb-atlas-operator-6db86785d8-4mtsq manager github.com/mongodb/mongodb-atlas-kubernetes/pkg/controller/atlasdeployment.(*AtlasDeploymentReconciler).ensureAdvancedDeploymentState(0x0?, 0x400031c500, 0x400002e000, 0x40005a2480)
mongodb-atlas-operator-6db86785d8-4mtsq manager 	/home/runner/work/mongodb-atlas-kubernetes/mongodb-atlas-kubernetes/pkg/controller/atlasdeployment/advanced_deployment.go:65 +0x644
mongodb-atlas-operator-6db86785d8-4mtsq manager github.com/mongodb/mongodb-atlas-kubernetes/pkg/controller/atlasdeployment.(*AtlasDeploymentReconciler).handleAdvancedDeployment(0x164d7c8?, {0x164a810, 0x4000bd7ce0}, 0x400031c500, 0x400002e000, 0x40005a2480, {{{0x163b2b8?, 0x4000b411c0?}, {0x16335e0?, 0x4000b411d0?}}})
mongodb-atlas-operator-6db86785d8-4mtsq manager 	/home/runner/work/mongodb-atlas-kubernetes/mongodb-atlas-kubernetes/pkg/controller/atlasdeployment/atlasdeployment_controller.go:379 +0x58
mongodb-atlas-operator-6db86785d8-4mtsq manager github.com/mongodb/mongodb-atlas-kubernetes/pkg/controller/atlasdeployment.(*AtlasDeploymentReconciler).Reconcile(0x400040ecf0, {0x164a810, 0x4000bd7ce0}, {{{0x4000f80f50, 0x7}, {0x4000f80f40, 0xf}}})
mongodb-atlas-operator-6db86785d8-4mtsq manager 	/home/runner/work/mongodb-atlas-kubernetes/mongodb-atlas-kubernetes/pkg/controller/atlasdeployment/atlasdeployment_controller.go:191 +0x1b3c
mongodb-atlas-operator-6db86785d8-4mtsq manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x164a810?, {0x164a810?, 0x4000bd7ce0?}, {{{0x4000f80f50?, 0x110e280?}, {0x4000f80f40?, 0x0?}}})
mongodb-atlas-operator-6db86785d8-4mtsq manager 	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122 +0x8c
mongodb-atlas-operator-6db86785d8-4mtsq manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0x40003a4500, {0x164a848, 0x4000315680}, {0x12258c0?, 0x4000991460?})
mongodb-atlas-operator-6db86785d8-4mtsq manager 	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323 +0x29c
mongodb-atlas-operator-6db86785d8-4mtsq manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0x40003a4500, {0x164a848, 0x4000315680})
mongodb-atlas-operator-6db86785d8-4mtsq manager 	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274 +0x198
mongodb-atlas-operator-6db86785d8-4mtsq manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
mongodb-atlas-operator-6db86785d8-4mtsq manager 	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235 +0x74
mongodb-atlas-operator-6db86785d8-4mtsq manager created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 87
mongodb-atlas-operator-6db86785d8-4mtsq manager 	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:231 +0x43c
```

**Operator Information**
image: docker.io/mongodb/mongodb-atlas-kubernetes-operator:1.9.0

**Kubernetes Cluster Information**
EKS version: v1.27.4-eks-2d98532

**Comment by josvazg** [comment] 2023-10-24 11:00
Hi, @viktorradnai

Sorry to hear that you are having issues using the Atlas Operator.
We will look into avoiding those panics, but the fix will probably be done by rejecting the Custom Resource definition at validation time, which will not solve your issue.

The Atlas Operator is designed to fully own an Atlas project & deployment combo, including its dependencies, like user definitions.  This is by design as Operators are usually thought to fully automate the deployment and live management of infrastructure as code setups.

In this case we would suggest you can either manage everything from Terraform or allow the Operator to fully manage the deployment.

**Comment by viktorradnai** [comment] 2023-10-24 12:36
Hi @josvazg , thanks for the quick reply. The validation fix makes sense based on the use cases you are intending the operator for.

Also thanks for clarifying the design intention. It seems like the operator isn't a great match for our use case and we will not be adopting it at this point but we'll follow its development.

**Comment by josvazg** [comment] 2023-12-05 12:57
I am closing this one now @viktorradnai, but please, do no hesitate to re-open if you have related concerns.

**Closed as completed by josvazg** 2023-12-05 12:57 UTC
Labels: no-issue-activity
