### ISSUE TITLE
Undefined functions in main branch

### ISSUE THREAD

**Issue by jianrongzhang89** [mongodb/mongodb-atlas-kubernetes#667] opened 2022-09-02 13:38 UTC
Clone the repo and switch to main branch.
Run go vet and it fails with missing symbol checkUpAWSEnviroment.
jianrzha-mac:mongodb-atlas-kubernetes zhangj$ make vet
go vet ./...
# github.com/mongodb/mongodb-atlas-kubernetes/test/e2e_test
vet: test/e2e/cloud_access_role_test.go:28:3: undeclared name: checkUpAWSEnviroment
make: *** [vet] Error 2

**Comment by yzdann** [comment] 2022-09-02 13:44
Might related to this :
https://github.com/mongodb/mongodb-atlas-kubernetes/pull/613/files#diff-93b46b0715181c9cf397eed60862261b7839ff721599fcc393a393b9edea610b

**Comment by fabritsius** [comment] 2022-09-02 13:44
This is strange as this function is actually [defined in the same package](https://github.com/mongodb/mongodb-atlas-kubernetes/blob/0a7bd85c57dd21ff9dbbcfc009ff34a0659bb795/test/e2e/e2e_suite_test.go#L56).

Calling `go vet` doesn't return any errors for me. Can this issue be caused by the changes in your branch?

**Comment by fabritsius** [comment] 2022-09-02 13:46
Ah, yeah, my mistake. I also wasn't on the `main` branch and @yzdann suggestion is correct 👍

**Comment by jianrongzhang89** [comment] 2022-09-02 13:49
@fabritsius @yzdann there are other errors from the linter:
Running [/home/runner/golangci-lint-1.46.2-linux-amd64/golangci-lint run --out-format=github-actions --timeout 10m] in [] ...
  Error: undeclared name: `checkUpAWSEnviroment` (typecheck)
  Error: too many arguments in call to actions.DeployProject
  	have (*model.TestDataProvider, string)
  	want (*model.TestDataProvider) (typecheck)
  Error: undeclared name: `checkUpAWSEnviroment` (typecheck)
  Error: undeclared name: `checkUpAzureEnviroment` (typecheck)
  Error: undeclared name: `checkNSetUpGCPEnviroment` (typecheck)
  Error: too many arguments in call to actions.DeployProject
  	have (*model.TestDataProvider, string)
  	want (*model.TestDataProvider) (typecheck)
  Error: SA1019: strings.Title has been deprecated since Go 1.18 and an alternative has been available since Go 1.0: The rule Title uses for word boundaries does not handle Unicode punctuation properly. Use golang.org/x/text/cases instead.  (staticcheck)

**Comment by Sugar-pack** [comment] 2022-09-02 13:49
Hi @jianrongzhang89. Thank you for creating the issue. This issue has been fixed in this PR: https://github.com/mongodb/mongodb-atlas-kubernetes/pull/664

**Comment by jianrongzhang89** [comment] 2022-09-02 13:53
Thank you so much @Sugar-pack

**Closed** 2022-09-02 13:54 UTC
